/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/
-- select * from [gold].[dim_customers]
-- select * from [gold].[dim_products]
-- select * from [gold].[fact_sales]



-- 1. Find total customers by countries
select 
    country,
    count(customer_id) as total_customer 
from [gold].[dim_customers] 

group by country 
order by total_customer desc;



-- 2. Find total customers by gender
select  
    gender,
    count(customer_id) as total_customer 
from [gold].[dim_customers] 

group by gender
order by total_customer desc;




-- 3. Find total products by category
select  
        category,
        count(product_id) as total_product 
from [gold].[dim_products] 

group by category
order by total_product desc;


-- 4. What is the average costs in each category?
select 
        category ,
        avg(cost) as avg_cost
from [gold].[dim_products] 

group by category
order by avg_cost desc;



-- 5. What is the total revenue generated for each category?
select 
    dp.category,
    sum(fs.price * fs.quantity ) as total_revenue 
from gold.fact_sales fs

left join gold.dim_products dp
on fs.customer_key = dp.product_id

group by dp.category
order by total_revenue desc;



-- 6. What is the total revenue generated by each customer?
select 
            dc.customer_key,
            dc.first_name,
            dc.last_name, 
            sum(fs.price * fs.quantity) as total_revenue
from gold.fact_sales fs 
left join gold.dim_customers dc
on dc.customer_key = fs.customer_key 

group by dc.customer_key,
            dc.first_name,
            dc.last_name

order by total_revenue desc;




-- 7. What is the distribution of sold items across countries?
select 
    dc.country, 
    count(fs.quantity) as total_sold 

from gold.dim_customers dc
left join gold.fact_sales fs
on dc.customer_key = fs.customer_key

group by dc.country
order by total_sold desc;

